### ISSUE TITLE
Dynamic icons not showing up

### ISSUE THREAD

**Issue by bart** [JensDll/tailwindcss-plugin-icons#10]
Hey @JensDll,

first of all thanks a lot for the great plugin. Especially the latest feature of being able to include all icons of a set is super helpful. I'm using your plugin in one of my latest projects and came up with an issue related to dynamic classes. I want to display icons from the circle-flag package like this:

```
// Does not work
<span :class="`i-circle-flags-${language} w-4 h-4 block`" />

// Does work
<span :class="`i-circle-flags-en w-4 h-4 block`" />
```

In HTML it get's rendered correctly but it doesn't get displayed. When I do it statically it works well. Also it works if I create a separate page where I add all icons as static ones then also the dynamic ones get rendered. I'm not sure if it has something to do with your library or the Vue 3 Vitesse template setup I'm using.

Any help would highly appreciated, thanks in advance!

**Comment by JensDll** [comment]
Hey, I think you're running into one of Tailwind's class detection caveats. See [this section on dynamic class names](https://tailwindcss.com/docs/content-configuration#dynamic-class-names):

> The most important implication of how Tailwind extracts class names is that it will only find classes that exist as complete unbroken strings in your source files.

That's why the dynamic ones only work if Tailwind sees them statistically elsewhere.

**Comment by bart** [comment]
Working with Tailwind for years now but didn't take this note serious enough yet. Thank you very much!
