### ISSUE TITLE
Prefix configuration

### ISSUE THREAD

**Issue by ineshbose** [JensDll/tailwindcss-plugin-icons#11]
Can the plugin possibly add an option to configure the prefix `i-`?

Similar to the use case described in https://github.com/JensDll/tailwindcss-plugin-icons/issues/8#issuecomment-1257759676, the library would use `bi-arrow` internally in the components instead of `i-bi-arrow`.

**Comment by JensDll** [comment]
It's not much effort to add. But unless this is blocking you, I strongly dislike stylistic configuration.
